name: Telegram Webhook

on:
  repository_dispatch:
    types: [telegram_file]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Process file
        env:
          EVENT_DATA: ${{ toJson(github.event.client_payload) }}
        run: |
          # Устанавливаем jq
          sudo apt-get install -y jq
          
          # Извлекаем данные
          FILENAME=$(echo "$EVENT_DATA" | jq -r '.file_name')
          CONTENT=$(echo "$EVENT_DATA" | jq -r '.file_content')
          
          # Сохраняем файл
          mkdir -p results.jsons
          echo "$CONTENT" > "results.jsons/$FILENAME"
          
          # Коммитим
          git config --global user.name "Telegram Bot"
          git add .
          git commit -m "Add $FILENAME"
          git push
